#
# (C) Copyright 2003-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= board.o
obj-y  += lowlevel_init.o
obj-y  += lwip_start.o
obj-y  += httpd.o
obj-y  += wget.o
obj-y  += y2_image.o
obj-y  += getopt.o
obj-y  += factory.o
obj-y  += led.o

# used by wget to pars http headers from server. 
obj-y  += http-parser/http_parser.o

# webserver.
obj-y  += httpserver_raw/httpd.o
obj-y  += httpserver_raw/fs.o

